### ISSUE TITLE
Laborratte und Spielwiese (siehe #8 und #2)

### ISSUE THREAD

**Issue by ghost** [TheNeoGameFactory/GWJ20-GodotCommunityDE#1]
- es wurde eine Laborratte hinzugefügt (mit Textur): .glb-Datei und vererbte .tscn
was noch fehlt: Rigging / Animation
- Switch nach GLES2 (kann in einem späteren Commit wieder geändert werden)
- Es gibt weiterhin keine Hauptszene

**Comment by ghost** [comment]
Die Spielwiese ist dazu da, um Steuerung oder Pathfinding auszutesten.
Da es sich um ein 3D-Spiel handelt, auch mit leichten Hügeln.
Bitte #8 zuerst mergen.

**Comment by TheNeoGameFactory** [comment]
Nein, es handelt sich nicht um ein Spiel mit leichten Hügeln und es braucht auch kein Pathfinding weil es keine Gegner gibt.

Habe ich schon lange bei Discord geschrieben. LESEN

**Comment by ghost** [comment]
Die Laborratte kann aber immer noch unabhängig gemerged werden.
