### ISSUE TITLE
Easter Egg

### ISSUE THREAD

**Issue by TheNeoGameFactory** [TheNeoGameFactory/GWJ20-GodotCommunityDE#12]
Das Easter Egg mit dem x Minuten still stehen, damit die Ratte frei kommt, übernimmst du das HugeGameArtGD?

Dadurch das du die Steuerung übernimmst kannst du das gleich mit abfragen.

**Comment by TheNeoGameFactory** [comment]
Gleich mit der Wiese und dem Riesen Ei, wenn möglich ;)

**Comment by ghost** [comment]
Gut, dann mache ich das 👍

**Comment by JohnNitrous** [comment]
Wollen wir hier gleich alle Easteregg Ideen sammeln?

**Comment by TheNeoGameFactory** [comment]
Nein, die zwei reichen ja wohl, und deine Idee kannst noch für unsere Community lassen ;)

**Comment by TheNeoGameFactory** [comment]
Hier wurde im Übrigen auch nur für Hälfte gemacht.

Der Timer für das easter Egg fehlt.
Schön das wir ein Ei und die Wiese haben aber keinen Timer der das triggert....


Ist wieder offen, muss noch nachgeliefert werden!

**Comment by ghost** [comment]
Wird es ausgelöst, wenn die Ratte x Minuten still steht oder bei einem bestimmten Event, bei dem der Laborant abgelenkt ist und die Ratte frei kommt (kein Zurücksetzen)?

**Comment by TheNeoGameFactory** [comment]
Wenn der Spieler x Minuten keine Eingabe macht. Also ja die Maus sich nicht bewegt.

Denke da an 2-5 Minuten Spanne, oder?

**Comment by jonathan-wolt** [comment]
ich fände 2-3 min optimal. Dann ist es nicht so lang, dass man nie das Easter-Egg "findet" und nicht so kurz, dass man kurz die Maus nicht bewegt und schon ist es da

**Comment by ghost** [comment]
Habe jetzt 140 Sekunden genommen, also 2 Minuten 20 Sekunden. Kann man zum Testen natürlich verringern, macht gerade nur einen Print.
