### ISSUE TITLE
Eventuell doch noch drittes easter egg

### ISSUE THREAD

**Issue by TheNeoGameFactory** [TheNeoGameFactory/GWJ20-GodotCommunityDE#18]
Den konami Code einbinden.

Müssen dann nur Mal schauen was dann passieren soll 😅 
Ob es da nicht sogar reicht das der Laborant einfach ein Kommentar dazu abgibt.

Was meint ihr?

https://en.m.wikipedia.org/wiki/Konami_Code

**Comment by jonathan-wolt** [comment]
Glaube schon das das reicht. Wir  könnten es aber auch so machen, dass die Hand die Ratte hochhept und dann an irgendeiner anderen Stelle wieder absetzt. Das wäre interessanter als nur eine Kommentar vom Laboranten

**Comment by jonathan-wolt** [comment]
ich könnte den code schreiben, der überprüft, ob gerade der konami-code gedrückt wurde

**Comment by TheNeoGameFactory** [comment]
Okay, und dann löst er ein Event aus, dann kann man immer noch das easter Egg machen, welches einfach das Event abfragt und dann ausgeführt wird 👍

**Comment by TheNeoGameFactory** [comment]
Dadurch ist dein Code sehr flexibel

**Comment by jonathan-wolt** [comment]
Ich hab jetzt einen Code geschrieben, der genau das überprüft. Damit das klappt muss der Code in den autoload. Bis jetzt wird nur erst "yeah, yeah, yeah!!!" geprintet, wenn der Conami-Code eingegeben wurde. Statt diesem Print könnte man natürlich ein Signal senden oder irgendetwas anderes machen

**Comment by TheNeoGameFactory** [comment]
Erledigt
