### ISSUE TITLE
Musik im menü hinzufügen

### ISSUE THREAD

**Issue by TheNeoGameFactory** [TheNeoGameFactory/GWJ20-GodotCommunityDE#22]
Sorry, dafür hatte ich gerade keine Zeit mehr, bitte die Musik hinzufügen, nur einer nicht alle ;)

Wer machts?

**Comment by jonathan-wolt** [comment]
kann ich machen

**Comment by TheNeoGameFactory** [comment]
Hattest du glaube schon erledigt?
Hattest du glaube bei discord geschrieben, richtig?

**Comment by jonathan-wolt** [comment]
ja

**Comment by jonathan-wolt** [comment]
ich sende gleich einen pull request

**Comment by jonathan-wolt** [comment]
hab bloß vergessen im komment zu schreiben, dass es das hier fixt. ist hoffentlic nicht so schlimm

**Comment by TheNeoGameFactory** [comment]
Erledigt
