### ISSUE TITLE
Splashscreen

### ISSUE THREAD

**Issue by TheNeoGameFactory** [TheNeoGameFactory/GWJ20-GodotCommunityDE#24]
Splashscreen mit folgenden Logos

GodotCommunityDE

GodotWildJam

Dann die drei Karten, weil wir alles integrieren.

Am schönsten wären die drei Karten übereinander, die dann ausgefächert werden.
So als ob man Karten in der Hand hält.

Danach der Titel des Spieles und dann das Thema.

Wer möchte das machen?

Da es Recht lang wird, entweder von Anfang an das man jedes einzelne mit ESC überspringen kann, oder beim ersten mal muss man es sich anschauen und an den zweiten Start kann man es überspringen.

Machbar?
Wer möchte?

**Comment by TheNeoGameFactory** [comment]
https://itch.io/jam/godot-wild-jam-20

Hier gibt's die Logos und Wildcards
https://drive.google.com/drive/folders/12rPUdx4XyaOoynIn2L29OZsKINDJeRT1?usp=sharing

**Comment by jonathan-wolt** [comment]
machbar: ja
wird bloß ein bisschen zeit in anspruch nehmen. Kann ich aber gerne machen oder zumindest schon mal anfangen
