### ISSUE TITLE
Rat.glb - was geht da ab?

### ISSUE THREAD

**Issue by TheNeoGameFactory** [TheNeoGameFactory/GWJ20-GodotCommunityDE#27]
Linux, das war deine oder?

Wieso sind in der Import Datei von der Ratte 256 Plätze für Animationsclips?
Ist das Standard, kann man das reduzieren?

Wenn ja, bitte reduzieren!

**Comment by ghost** [comment]
Das ist der Blender-Standard, vielleicht kann man das reduzieren.

**Comment by ghost** [comment]
Also ist bei jedem File so, also beispielsweise auch beim rat.dae import file (nicht nur GLB).
Habe schon versucht, die Animation in Blender in den Export-Optionen zu deaktivieren, aber ist trotzdem drin.

**Comment by ghost** [comment]
Da hilft nur, es manuell rauszulöschen, bei jedem Neuimport in Godot ist es aber wieder drin, auch ohne Häkchen bei Animation.

**Comment by TheNeoGameFactory** [comment]
Hm 🤔 okay
