### ISSUE TITLE
Grundgerüst Level

### ISSUE THREAD

**Issue by TheNeoGameFactory** [TheNeoGameFactory/GWJ20-GodotCommunityDE#4]
Wer von euch möchte das Grundgerüst vom Level übernehmen?

**Comment by JohnNitrous** [comment]
Darf ich?

**Comment by TheNeoGameFactory** [comment]
Da du Recht schnell bist und sauber arbeitest, gerne.

**Comment by ghost** [comment]
Habe schon einen Platzhalter gefunden.

**Comment by JohnNitrous** [comment]
Dann bin ich dran, bei der Gelegenheit werde ich auch gleich meine Ratte mitgeben.

**Comment by JohnNitrous** [comment]
Simples Grundgerüst des Levels und ein Modell der Ratte ist nun in meinem Fork.

**Comment by ghost** [comment]
Ist bereits spielbar.
