### ISSUE TITLE
Steuerung

### ISSUE THREAD

**Issue by TheNeoGameFactory** [TheNeoGameFactory/GWJ20-GodotCommunityDE#5]
Wir benötigen eine grobe Steuerung für die Ratte.

Wer macht's?

**Comment by ghost** [comment]
Kann ich machen.

**Comment by TheNeoGameFactory** [comment]
Alles klar, aber simpel halten.
Erstmal nur sowas wie in alle Richtungen, kein Springen oder Ducken.

Versuche das die Figur sich schön dreht und nicht schlagartig die Richtung ändert.

**Comment by ghost** [comment]
Die Ratte dreht sich derzeit mit den Pfeiltasten links/rechts, oben/unten dann für die Bewegung nach vorne/hinten.
Was auch gehen würde, wäre eine Richtung durch die Pfeiltasten vorzugeben, aber dann müsste der Winkel berechnet werden und der Bewegungsvektor normalisiert werden, wäre dann also etwas komplizierter.

**Comment by TheNeoGameFactory** [comment]
Denke dass sollte so reichen.
